export struct ModuleMetadata {
    title: string,
    artist: string,
    copyright: string,

    driver: string,

    extended-metadata: bool,
    loop-detection: bool,
    extended-durations: [int],
    chips: [string],
    tracks: [string]
}

export component ModuleMetadataView {
    in property <ModuleMetadata> module-metadata: {
        title: "<?>",
        artist: "<?>",
        copyright: "<?>",
        driver: "<?>",
        extended-metadata: false,
        loop-detection: false,
        extended-durations: [],
        chips: [],
        tracks: []
    };

    VerticalLayout {
        alignment: center;
        spacing: 4px;

        Text {
            text: module-metadata.title;
            horizontal-alignment: center;
        }
        Text {
            text: module-metadata.artist;
            horizontal-alignment: center;
        }
        Text {
            text: module-metadata.copyright;
            horizontal-alignment: center;
        }
        HorizontalLayout {
            alignment: center;
            spacing: 16px;

            Text {
                text: "NSFe/NSF2 metadata";
                color: module-metadata.extended-metadata
                    ? green
                    : red;
            }
            Text {
                text: "Loop detection";
                color: module-metadata.loop-detection
                    ? green
                    : red;
            }
            Text {
                text: "NSFe/NSF2 duration";
                color: module-metadata.extended-durations.length > 0
                    ? green
                    : red;
            }
        }
        HorizontalLayout {
            alignment: center;
            spacing: 12px;

            for chip in module-metadata.chips : Rectangle {
                background: chip == "2A03" ? #dddddd :
                            chip == "FDS" ? #0066ff :
                            chip == "N163" ? #ff0000 :
                            chip == "MMC5" ? #2eb82e :
                            chip == "VRC6" ? #ffcc00 :
                            chip == "VRC7" ? #ff9800 :
                            chip == "S5B" ? #ff33cc :
                                            transparent;

                width: 36px;
                height: 18px;
                border-radius: 2px;

                Text {
                    horizontal-alignment: center;
                    vertical-alignment: center;
                    text: chip;

                    color: chip == "2A03" ? black :
                           chip == "VRC6" ? black :
                                            white;
                }
            }
        }
    }
}
